baseURL = "https://oj.pkachu.com/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh-Hans"
title = "Learn"
theme = "cayman-hugo-theme"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  # Header text, can be markdown
  project_name = " "
  project_tagline = " "

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "Talk is cheap. Show me the code."

  # True to open gitalk
  enableGitalk = true

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#8360c3"
  header_background_color_secondary = "#2ebf91"

  # Text colors
  section_headings_color = "#159957"
  body_text_color = "#606c71"
  body_link_color = "#1e6bb8"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]
  [[menu.nav]]
    name = "LeetCode"
    url = "/leetcode/"
    weight = 1
  [[menu.nav]]
    name = "O J"
    url = "/oj/"
    weight = 2
  [[menu.nav]]
    name = "Learn"
    url = "/"
    weight = 3
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.nav]]
    name = "Github"
    url = "https://github.com/threegeese/Online-Judge"
    weight = 5

# gitalk config
# https://github.com/gitalk/gitalk
[params.gitalk] 
  clientID = '59bb694f77474bbdddd0'
  clientSecret = '52ec4d1f65ce7ebed307100e000894710b8fce98'
  repo = 'dsaa'
  owner = 'threegeese'
  admin= ['threegeese']
  id= 'location.pathname'
  labels= 'gitalk'
  perPage= 15
  pagerDirection= 'last'
  createIssueManually= false
  distractionFreeMode= false